---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: be-login-ui-develop
    namespace: fawry-user-app
spec:
  selector:
    matchLabels:
      name: be-login-ui-develop
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: be-login-ui-develop
    spec:
      containers:
      - name: be-login-ui-alpha
        image: node2:5000/be-login-ui-develop:BUILDID
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: https
        env:
        - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
          value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
        - name: BUILD_ENV
          value: "dev"
        - name: BUILD_ID
          value: 'BUILDID'