FROM node2:5000/node:12.18.1
WORKDIR /opt/app
RUN rm -rf /opt/app
COPY . /opt/app/
RUN npm cache clean --force

#RUN npm  --registry http://10.95.0.75:8089/repository/npm-proxy/ --verbose install --no-package-lock

RUN npm --registry http://10.95.0.2:8081/repository/npm-proxy/  --verbose install sonarqube-scanner --save-dev
RUN npm  --registry http://10.95.0.2:8081/repository/npm-proxy/ --verbose install --no-package-lock
RUN node_modules/.bin/ng build --prod --configuration=app_profile --output-path=/opt/app/dist
RUN npm run sonar
