#FROM nginx

FROM node2:5000/nginx:k8s
EXPOSE 80 443
RUN rm -rf /usr/share/nginx/html/*
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY ./dist/  /usr/share/nginx/html/
CMD ["nginx", "-g", "daemon off;"]

RUN apt-get update && apt-get -y install sudo
#RUN adduser --disabled-password --gecos '' agent
#RUN adduser agent sudo
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
USER agent
WORKDIR /home/agent
RUN sudo apt-get  install curl -y
RUN curl -fsSL https://get.docker.com -o get-docker.sh
RUN sudo sh get-docker.sh
RUN sudo usermod -aG docker agent

RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl
RUN sudo  mv ./kubectl /usr/local/bin/kubectl

USER root