---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: be-login-ui-alpha
  name: be-login-ui-alpha
  namespace: fawry-user-app
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
      nodePort: 30818
  selector:
    name: be-login-ui-alpha
