---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: be-login-ui-develop
  name: be-login-ui-develop
  namespace: business-entity-app
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80
      nodePort: 30815
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
      nodePort: 30816
  selector:
    name: be-login-ui-develop